name: Android Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 74db5e5
      - name: Build Android
        run: |
          ndk-build -j$(nproc) APP_PLATFORM=android-21 APP_ABI=arm64-v8a
      - uses: actions/upload-artifact@v3
        with:
          name: gpsp_android
          path: libs/arm64-v8a/*.so
